pre job이 실패하면 다음 job도 실패하는지 테스트해보기

diff --git a/chart/hello-world-server/templates/pre-post-sync.yaml b/chart/hello-world-server/templates/pre-post-sync.yaml
--- a/chart/hello-world-server/templates/pre-post-sync.yaml
+++ b/chart/hello-world-server/templates/pre-post-sync.yaml
@@ -6,7 +6,7 @@ metadata:
   annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/sync-wave: "1"
-    argocd.argoproj.io/hook-delete-policy: HookSucceeded
+{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
 spec:
   ttlSecondsAfterFinished: 100
   template:
@@ -18,7 +18,7 @@ spec:
             - /bin/bash
             - -c
             - |
-              echo "Pre Sync Job 1"
+              echo "Pre Sync Job 1 - Fail" ; exit 1
       restartPolicy: Never
   backoffLimit: 2
 ---
@@ -29,9 +29,9 @@ metadata:
   annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/sync-wave: "2"
-    argocd.argoproj.io/hook-delete-policy: HookSucceeded
+{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
 spec:
-  ttlSecondsAfterFinished: 600
+  ttlSecondsAfterFinished: 100
   template:
     spec:
       containers:
@@ -51,9 +51,9 @@ metadata:
   generateName: postsync-job
   annotations:
     argocd.argoproj.io/hook: PostSync
-    argocd.argoproj.io/hook-delete-policy: HookSucceeded
+{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
 spec:
-  ttlSecondsAfterFinished: 600
+  ttlSecondsAfterFinished: 100
   template:
     spec:
       containers:
@@ -75,7 +75,7 @@ metadata:
     argocd.argoproj.io/hook: SyncFail
     argocd.argoproj.io/hook-delete-policy: HookSucceeded
 spec:
-  ttlSecondsAfterFinished: 600
+  ttlSecondsAfterFinished: 100
   template:
     spec:
       containers:
